Extra () caused error in clang:
monitoring/instrumented_mutex.cc:20:114: error:
  PerfStepTimer perf_step_timer_db_mutex_lock_nanos(&(perf_context.db_mutex_lock_nanos), true);
 if ((stats_code_ == DB_MUTEX_WAIT_MICROS)) { perf_step_timer_db_mutex_lock_nanos.Start(); };
       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
monitoring/instrumented_mutex.cc:20:114: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]

Signed-off-by: Daniel Black <daniel.black@au.ibm.com>